@startuml

abstract class Producto {
    + IdProducto: String;
    + Modelo: String;
}

class CPU {
    + MemoriaPrincipal: String;
}

class Impresora {
    + VelocidadImpresion: String;
}

class Monitor {
    + ResolucionMaxima: String;
}

class DiscoDuro {
    + CapacidadAlmacenamiento: int;
}

abstract class AltaTecnologia {
    + EmpresaFabricante: EmpresaFabricante;
    + IdAltaTecno: String;
    + PaisOrigen: String;
    + FechaFabricacion: Date;
    + Precio: Double; 
}

abstract class SoporteTecnico {
    + IdSoporte: String;
    + DetalleServicio: String;
    + Precio: double;
    + Totalfactura: double;
}

class ServicioTecnicoImpresora {
    + ServicioEsclusivo: String;
}

class EmpresaFabricante {
    + IdEmpresa: String;
    + Nombre: String;
    + Direccion: String;
    + NumeroEmpleados: int;
}

class Proveedor {
    + NIF: String;
    + Direccion: String;
    + IdProveedor: String;
}

class ProductoProveedor {
    + IdProducto: Producto;
    + IdProveedor: Proveedor;
    + FechaAdquisicion: Date;
}

abstract class Alquiler {
    + Codigo: String;
    + PrecioPorHora: double;
    + IdAlquiler: String;
}

abstract class Cliente {
    + Nombre: String;
    + IdCliente: String;
}

class ClienteImpresora {
    + DNI: String;
    + Telefono: String;
    + Direccion: String;
}

class Contrato {
    + IdContrato: String;
    + Modalidad: String;
    + FechaInicio: Date;
    + FechaFin: Date;
    + Detalle: String;
}

class Factura {
    + IdFactura: String;
    + NombreProducto: String;
    + fechaCompra: Date;
    + NombreEmpresa: String;
    + Precio: Double; 
    + MetodoPago: String;
}

//corregido? 
class Factura {
    + IdFactura: String;
    + Producto: Producto;
    + Empresa: EmpresaFabricante;
    + FechaCompra: Date;
    + Precio: double;
    + MetodoPago: String;
}

relaciones 


